# Generated by Django 5.1.6 on 2025-03-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_imagecf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageCF',
        ),
    ]
