# Generated by Django 5.1.6 on 2025-03-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_calendar', '0002_remove_objetive_theme_objetive_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='objectives',
            field=models.ManyToManyField(blank=True, to='custom_calendar.objetive'),
        ),
    ]
