# Generated by Django 5.1.6 on 2025-03-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_calendar', '0003_theme_objectives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='objectives',
        ),
    ]
