# Generated by Django 5.1.6 on 2025-03-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_calendar', '0004_remove_theme_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
