# Generated by Django 5.1.6 on 2025-03-14 02:54

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_calendar', '0005_alter_theme_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=storages.backends.s3.S3Storage, upload_to='images_custom_calendar/')),
            ],
        ),
        migrations.AddField(
            model_name='objetive',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_calendar.imagecf'),
        ),
    ]
