# Generated by Django 5.1.6 on 2025-03-14 03:33

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_calendar', '0006_imagecf_objetive_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecf',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage, upload_to='images/custom_calendar/'),
        ),
    ]
