# Generated by Django 5.1.6 on 2025-03-14 23:23

import custom_calendar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_calendar', '0010_alter_imagecf_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecf',
            name='image',
            field=models.ImageField(storage=custom_calendar.models.PrivateMediaStorage(), upload_to='objectives_images/'),
        ),
    ]
