# Generated by Django 5.1.6 on 2025-03-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetive',
            name='theme',
        ),
        migrations.AddField(
            model_name='objetive',
            name='themes',
            field=models.ManyToManyField(blank=True, to='custom_calendar.theme'),
        ),
    ]
