# Generated by Django 5.1.6 on 2025-03-14 19:30

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_calendar', '0008_imagecf_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecf',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage, upload_to='images/'),
        ),
    ]
