# Generated by Django 5.1.6 on 2025-03-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_calendar', '0012_alter_imagecf_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcalendar',
            name='format',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
